version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Make sure frontend has its Dockerfile
    ports:
      - "3000:3000"  # Expose React app on port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
